/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BoardsMemberships
 */
export interface BoardsMemberships {
    /**
     * all or a comma-separated list of: avatarHash, bio, bioData, confirmed, fullName, idPremOrgsAdmin, initials, memberType, products, status, url or username
     * @type {string}
     * @memberof BoardsMemberships
     */
    'member_fields'?: string;
    /**
     * One of: admin, normal or observer
     * @type {string}
     * @memberof BoardsMemberships
     */
    'type'?: string;
}

