/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BoardsLists
 */
export interface BoardsLists {
    /**
     * a string with a length from 1 to 16384
     * @type {string}
     * @memberof BoardsLists
     */
    'name'?: string;
    /**
     * A position. top , bottom , or a positive number.
     * @type {string}
     * @memberof BoardsLists
     */
    'pos'?: string;
}

