/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Boards
 */
export interface Boards {
    /**
     *  true or false
     * @type {string}
     * @memberof Boards
     */
    'closed'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'desc'?: string;
    /**
     * The id of the board to copy into the new board
     * @type {string}
     * @memberof Boards
     */
    'idBoardSource'?: string;
    /**
     * The id or name of the organization to add the board to.
     * @type {string}
     * @memberof Boards
     */
    'idOrganization'?: string;
    /**
     * Components of the source board to copy.
     * @type {string}
     * @memberof Boards
     */
    'keepFromSource'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'labelNames/blue'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'labelNames/green'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'labelNames/orange'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'labelNames/purple'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'labelNames/red'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'labelNames/yellow'?: string;
    /**
     * a string with a length from 1 to 16384
     * @type {string}
     * @memberof Boards
     */
    'name'?: string;
    /**
     * all or a comma-separated list of: calendar, cardAging, recap or voting
     * @type {string}
     * @memberof Boards
     */
    'powerUps'?: string;
    /**
     * A standard background name, or the id of a custom background
     * @type {string}
     * @memberof Boards
     */
    'prefs/background'?: string;
    /**
     *  true or false
     * @type {string}
     * @memberof Boards
     */
    'prefs/calendarFeedEnabled'?: string;
    /**
     * One of: pirate or regular
     * @type {string}
     * @memberof Boards
     */
    'prefs/cardAging'?: string;
    /**
     *  true or false
     * @type {string}
     * @memberof Boards
     */
    'prefs/cardCovers'?: string;
    /**
     * One of: disabled, members, observers, org or public
     * @type {string}
     * @memberof Boards
     */
    'prefs/comments'?: string;
    /**
     * One of: admins or members
     * @type {string}
     * @memberof Boards
     */
    'prefs/invitations'?: string;
    /**
     * One of: org, private or public
     * @type {string}
     * @memberof Boards
     */
    'prefs/permissionLevel'?: string;
    /**
     *  true or false
     * @type {string}
     * @memberof Boards
     */
    'prefs/selfJoin'?: string;
    /**
     * One of: disabled, members, observers, org or public
     * @type {string}
     * @memberof Boards
     */
    'prefs/voting'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Boards
     */
    'prefs_background'?: string;
    /**
     * One of: pirate or regular
     * @type {string}
     * @memberof Boards
     */
    'prefs_cardAging'?: string;
    /**
     *  true or false
     * @type {string}
     * @memberof Boards
     */
    'prefs_cardCovers'?: string;
    /**
     * One of: disabled, members, observers, org or public
     * @type {string}
     * @memberof Boards
     */
    'prefs_comments'?: string;
    /**
     * One of: admins or members
     * @type {string}
     * @memberof Boards
     */
    'prefs_invitations'?: string;
    /**
     * One of: org, private or public
     * @type {string}
     * @memberof Boards
     */
    'prefs_permissionLevel'?: string;
    /**
     *  true or false
     * @type {string}
     * @memberof Boards
     */
    'prefs_selfJoin'?: string;
    /**
     * One of: disabled, members, observers, org or public
     * @type {string}
     * @memberof Boards
     */
    'prefs_voting'?: string;
    /**
     *  true or false
     * @type {string}
     * @memberof Boards
     */
    'subscribed'?: string;
}

