/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardsChecklists
 */
export interface CardsChecklists {
    /**
     * The id of the source checklist to copy into a new checklist.
     * @type {string}
     * @memberof CardsChecklists
     */
    'idChecklistSource'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof CardsChecklists
     */
    'name'?: string;
    /**
     * The id of the checklist to add to the card, or null to create a new one.
     * @type {string}
     * @memberof CardsChecklists
     */
    'value'?: string;
}

