/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardsIdBoard
 */
export interface CardsIdBoard {
    /**
     * id of the list that the card should be moved to on the new board
     * @type {string}
     * @memberof CardsIdBoard
     */
    'idList'?: string;
    /**
     * id of the board the card should be moved to
     * @type {string}
     * @memberof CardsIdBoard
     */
    'value'?: string;
}

