/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardsStickers
 */
export interface CardsStickers {
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof CardsStickers
     */
    'image'?: string;
    /**
     * undefined
     * @type {string}
     * @memberof CardsStickers
     */
    'left'?: string;
    /**
     * undefined
     * @type {string}
     * @memberof CardsStickers
     */
    'rotate'?: string;
    /**
     * undefined
     * @type {string}
     * @memberof CardsStickers
     */
    'top'?: string;
    /**
     * Valid Z values for stickers, must be an integer
     * @type {string}
     * @memberof CardsStickers
     */
    'zIndex'?: string;
}

