/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Checklists
 */
export interface Checklists {
    /**
     * id of the board that the checklist should be added to
     * @type {string}
     * @memberof Checklists
     */
    'idBoard'?: string;
    /**
     * id of the card that the checklist should be added to
     * @type {string}
     * @memberof Checklists
     */
    'idCard'?: string;
    /**
     * The id of the source checklist to copy into a new checklist.
     * @type {string}
     * @memberof Checklists
     */
    'idChecklistSource'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Checklists
     */
    'name'?: string;
    /**
     * A position. top , bottom , or a positive number.
     * @type {string}
     * @memberof Checklists
     */
    'pos'?: string;
}

