/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Labels
 */
export interface Labels {
    /**
     * A valid label color or null
     * @type {string}
     * @memberof Labels
     */
    'color'?: string;
    /**
     * An id
     * @type {string}
     * @memberof Labels
     */
    'idBoard'?: string;
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof Labels
     */
    'name'?: string;
}

