/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ListsCards
 */
export interface ListsCards {
    /**
     * a string with a length from 0 to 16384
     * @type {string}
     * @memberof ListsCards
     */
    'desc'?: string;
    /**
     * A date, or null
     * @type {string}
     * @memberof ListsCards
     */
    'due'?: string;
    /**
     * A comma-separated list of objectIds, 24-character hex strings
     * @type {string}
     * @memberof ListsCards
     */
    'idMembers'?: string;
    /**
     * all or a comma-separated list of: blue, green, orange, purple, red or yellow
     * @type {string}
     * @memberof ListsCards
     */
    'labels'?: string;
    /**
     * a string with a length from 1 to 16384
     * @type {string}
     * @memberof ListsCards
     */
    'name'?: string;
}

