/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MembersBoardBackgrounds
 */
export interface MembersBoardBackgrounds {
    /**
     * One of: dark, light or unknown
     * @type {string}
     * @memberof MembersBoardBackgrounds
     */
    'brightness'?: string;
    /**
     * A file
     * @type {string}
     * @memberof MembersBoardBackgrounds
     */
    'file'?: string;
    /**
     *  true or false
     * @type {string}
     * @memberof MembersBoardBackgrounds
     */
    'tile'?: string;
}

