/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OrganizationsName
 */
export interface OrganizationsName {
    /**
     * A string with a length of at least 3.  Only lowercase letters, underscores, and numbers are allowed.  Must be unique.
     * @type {string}
     * @memberof OrganizationsName
     */
    'value'?: string;
}

