/*
Trello

This document describes the REST API of Trello as published by Trello.com.
 - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>
 - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Sessions
 */
export interface Sessions {
    /**
     * The id of the board you&#39;re viewing.  Boards with no viewers will not get updates about members&#39; statuses.
     * @type {string}
     * @memberof Sessions
     */
    'idBoard'?: string;
    /**
     * One of: active, disconnected or idle
     * @type {string}
     * @memberof Sessions
     */
    'status'?: string;
}

